### ISSUE TITLE
support typescript

### ISSUE THREAD

**Issue by Innei** [surmon-china/vue-codemirror#119] opened 2020-04-10 06:11 UTC
#### Vue.js version and component version

Vue.js 2

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/surmon/cp01hvq2/

#### What is Expected?

hope to add types.

#### What is actually happening?
![image](https://user-images.githubusercontent.com/41265413/78967463-2146e980-7b35-11ea-8353-3455ae462998.png)

**Comment by vintprox** [comment] 2020-04-10 09:45
I just was thinking about that 3 hours ago. Not a huge problem, I'd say, but could use some definitions of CodeMirror options [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/codemirror).

**Comment by TomRoSystems** [comment] 2020-04-13 13:54
This bug looks like a duplicate of #93

**Closed** 2020-05-29 14:53 UTC

**Comment by WesleyBatista** [comment] 2021-02-06 21:33
To **bypass** IDE warns and build problems you may try to create `src/vue-codemirror.d.ts` containing:
```ts
declare module "vue-codemirror";
```

PS: Visual Studio code requires a reload after that.
